### ISSUE TITLE
Validate website and helpUrl fields in manifest

### ISSUE THREAD

**Issue by ashryanbeats** [AdobeXD/xdpm#13]
https://github.com/AdobeXD/xdpm/blob/master/lib/validate.js

**Comment by yoshikinoko** [comment]
@ashryanbeats 
Shall we keep the issue opened? 

Due to recent console update, `manifest.json` no longer requires URLs 
https://adobexdplatform.com/plugin-docs/reference/structure/manifest.html

**Comment by ashryanbeats** [comment]
Ah, good point @yoshikinoko. Closing this since URLs are no longer required.
