### ISSUE TITLE
`npm install -g @adobe/xdpm` does not install dependent packages

### ISSUE THREAD

**Issue by yoshikinoko** [AdobeXD/xdpm#2]
#### Reproducing steps

1. ` npm install -g @adobe/xdpm`
2. `cd pugin-development-folder`
3.  `xdpm install`

then it throws following error

```
module.js:545
    throw err;
    ^

Error: Cannot find module 'cli'
...
```

Otherwise, `git clone`, `npm install` and `npm link` installation works fine.

**Comment by yoshikinoko** [comment]
I guess modifing package.json may fix this problem.

modify **devDependencies** to **dependencies**
https://github.com/AdobeXD/xdpm/blob/master/package.json#L28

**Comment by pklaschka** [comment]
@yoshikinoko Just asking: Can this be closed since the PR got merged?

**Comment by yoshikinoko** [comment]
@pklaschka thank you for ping me! (sorry, I missed the notification.)
