### ISSUE TITLE
Console update v2

### ISSUE THREAD

**Issue by yoshikinoko** [AdobeXD/xdpm#23]
Corresponding to https://github.com/AdobeXD/plugin-docs/pull/206,
Please update validator of `manifest.json` aka. `validate.js`

**Comment by yoshikinoko** [comment]
merged!
@kerrishotts thank you for your help.

**Comment by yoshikinoko** [comment]
@kerrishotts 
Sorry, I forgot to request one more thing. Please update the npm release to include this update.

**Comment by pklaschka** [comment]
I assume this is fixed now? We're now at version `v3.1.0`, which includes #9 and #30 .
