### ISSUE TITLE
Request: Validating the menus (uiEntryPoints)

### ISSUE THREAD

**Issue by yoshikinoko** [AdobeXD/xdpm#9]
Currently (v1.1.2),  xdpm checks if the `uiEntryPoints` exists or not. However, it would be better to check the "structure" of uiEntryPoints. 
For example, to check the nesting level of submenus, and required field.

https://github.com/AdobeXD/xdpm/blob/02698548e351162c89679379a072c50c5822f106/lib/validate.js#L90-L93

`xdpm` helped saved a lot of my development time, and I  believe that this tool accelerates the speed of developing plugins for many developers.

Thanks,

**Comment by ashryanbeats** [comment]
Agreed. I think this is something we want to do, but we need to make the time to do it. It won't make it in time for today's update, but I want to acknowledge that it's an idea we should work on.

**Comment by yoshikinoko** [comment]
Close the issue.
Already resolved with #23 (and PR of #24).
